#!/bin/bash
Rscript /var/www/wordpress/wp-content/plugins/sh-executor/scripts/004_Grafico_Preliminar.R
Rscript /var/www/wordpress/wp-content/plugins/sh-executor/scripts/005_Analisis_Grafico.R
Rscript /var/www/wordpress/wp-content/plugins/sh-executor/scripts/006_Distribucion_de_registros_por_comuna.R
Rscript /var/www/wordpress/wp-content/plugins/sh-executor/scripts/007_Dsitribucion_de_las_edades_de_las_victimas.R
Rscript /var/www/wordpress/wp-content/plugins/sh-executor/scripts/008_Distribución_de_los_distintos_tipos_de_violencia.R
Rscript /var/www/wordpress/wp-content/plugins/sh-executor/scripts/009_Violencia_cometida_hacia_las_mujeres.R
Rscript /var/www/wordpress/wp-content/plugins/sh-executor/scripts/010_Violencia_cometida_hacia_los_hombres.R
Rscript /var/www/wordpress/wp-content/plugins/sh-executor/scripts/011_Comparacion_actos_violentos.R
Rscript /var/www/wordpress/wp-content/plugins/sh-executor/scripts/012_Ingreso_registros_por_meses_genero.R
Rscript /var/www/wordpress/wp-content/plugins/sh-executor/scripts/013_Ingreso_Registros_Diferenciados_Mes_Genero.R
Rscript /var/www/wordpress/wp-content/plugins/sh-executor/scripts/014_Funcion_Graficar_Violencia_de_genero_sobre_genero.R
Rscript /var/www/wordpress/wp-content/plugins/sh-executor/scripts/015_Funcion_Graficar_violencia_por_edad_comuna_genero.R
Rscript /var/www/wordpress/wp-content/plugins/sh-executor/scripts/016_Funcion_graficar_3D_Edad_Comuna_Genero.R
Rscript /var/www/wordpress/wp-content/plugins/sh-executor/scripts/017_Funciones_Ejemplo.R
Rscript /var/www/wordpress/wp-content/plugins/sh-executor/scripts/018_Funciones_EstudioPreliminar.R
Rscript /var/www/wordpress/wp-content/plugins/sh-executor/scripts/021_Funciones_ParaEstudio_V3.R
Rscript /var/www/wordpress/wp-content/plugins/sh-executor/scripts/025_test_analiza_wp_upload_con_reporte_Pandoc_V2.R
Rscript /var/www/wordpress/wp-content/plugins/sh-executor/scripts/028_test_analiza_wp_upload_con_reporte_md_V4.R
